baseURL = "/"
languageCode = "en"
title = "GeoFS LiverySelector"
description = "A unified livery selector add-on for GeoFS"

theme = "docsy"

# Language settings
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

[params]
    name = "GeoFS LiverySelector"
    description = "Unified livery handler addon for GeoFS"

    copyright = "Kolos26"

    jstoc.enable = true # Use tocbot on the liveries page

    #email = "anthony.russel42@example.com"
    #phone = "+234 23 9873237"
    #address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2022
    avatar = "images/liveryselector-logo.svg"
    avatarclass = "rounded"
    background = ""
    banner = "featured-background.png"
    favicon = "images/liveryselector-logo-small.ico"
    DateForm = "January 2, 2006"
    author = "Kolos26"

    showSubheader = false
    showServices = false
    showRecentWorks = false
    showDownloads = true
    showClients = false

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1
[[menu.main]]
    name = "BLOG"
    url = "/blog/"
    weight = 20
[[menu.main]]
    name = "LIVERIES"
    url = "/liveries/"
    weight = 10
[[menu.main]]
    name = "ISSUES"
    url = "https://github.com/kolos26/GEOFS-LiverySelector/issues"
    weight = 100

[params.disqus]
    # site = "hugo-initio-site.disqus.com"

[params.sharethis]
    # property = "123456789012345678901234"
    # custom = true

[params.google.analytics]
    # trackerID = "GA-000000000-0"


[[params.social]]
	title = "github"
	url = "https://github.com/kolos26/GEOFS-LiverySelector"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""

[markup.goldmark.renderer]
    unsafe= true

###############################################################################
# Docsy-theme specific config customizations
###############################################################################

 [params.links]
  # End user relevant links. These will show up on left side of footer and in the community page if you have one.
  #[[params.links.user]]
  #  name = "Community forum"
  #  url = "https://community.cisco.com/t5/application-networking-and/bd-p/dev-app-networking"
  #  icon = "fa fa-envelope"
  #  desc = "Discussion and help from your fellow users"

  # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
  [[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/kolos26/GEOFS-LiverySelector"
    icon = "fab fa-github"
    desc = "Get involved with GeoFS LiverySelector development"
  [[params.links.developer]]
    name = "Discord"
    url = "https://discord.gg/ZW7zh9FXYN"
    icon = "fab fa-discord"
    desc = "Chat with the project developers"


[params.ui]
  #  Set to true to disable breadcrumb navigation.
  breadcrumb_disable = false
  # Set to true to disable the About link in the site footer
  footer_about_disable = false
  # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
  navbar_logo = true
  # Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
  navbar_translucent_over_cover_disable = false
  # Enable to show the side bar menu in its compact state.
  #sidebar_menu_compact = false
  # Enable to make the side bar menu foldable.
  sidebar_menu_foldable = true
  # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
  sidebar_search_disable = true


[sitemap]
  ChangeFreq = "daily"
  Priority = "1"

[security]
  [security.funcs]
    getenv = ['^HUGO_', 'PWD', '^DOC_', 'ENVIRONMENT']

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true

